version: "3"
services:

  frontend:
    image: projectwerk2/frontend:develop
    ports:
      - 80:5000
    restart: always
    environment:
     - REACT_APP_API_URL=http://192.168.99.100:8181

  backend:
    image: projectwerk2/backend
    ports:
      - 8181:8181
    environment:
      - APP_ENV=production
      - APP_KEY=${APP_KEY}

      - DB_HOST=database
      - DB_DATABASE=smartcampus
      - DB_USERNAME=smartcampus
      - DB_PASSWORD=smartcampus
    depends_on: 
      - database
    restart: always

  listener:
    image: projectwerk2/listener
    environment:
     - TTN_APPID=${TTN_APPID}
     - TTN_ACCESSKEY=${TTN_ACCESSKEY}
     - HTTP_HOST=backend
     - HTTP_PORT=8181
     - HTTP_PATH=/api/listener/
     - HTTP_HTTP=http
    restart: always

  database:
    image: mariadb
    environment:
     - MYSQL_ROOT_PASSWORD=smartcampus
     - MYSQL_DATABASE=smartcampus
     - MYSQL_USER=smartcampus
     - MYSQL_PASSWORD=smartcampus
    volumes:
     - database-data:/var/lib/mysql
    restart: always

volumes:
  database-data: